title: Cars
author: Turcu Cornel
email: cturc1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 on this web site we will be discussin the automotive world

# social links https://www.automotiveworld.com/
twitter_username: cornell/off
github_username: cornel1sam

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
